#ifndef DEFS_H
#define DEFS_H

#define FPS 60
#define SCREEN_WIDTH   1280
#define SCREEN_HEIGHT  720

#define MAX_SOUND_CHANNELS 8

#define MAX_KEYBOARD_KEYS 350

#define PLAYER_START_X 100
#define PLAYER_START_Y 100
#define PLAYER_SPEED 6
#define PLAYER_BULLET_SPEED 16
#define PLAYER_RELOAD_RATE 8
#define PLAYER_SPEEDUP_RATE 1.8
#define PLAYER_HEALTH 10

#define ENEMY_DY_MAX 2
#define ENEMY_DY_FACTOR 50.0
#define ENEMY_BASE_SPAWN_RATE 20
#define ENEMY_RAND_SPAWN_RATE 30
#define ENEMY_DX_MIN 2
#define ENEMY_DX_MAX 6
#define ENEMY_STARTING_HEALTH 2
#define ENEMY_BULLET_SPEED 10

#define SIDE_PLAYER 0
#define SIDE_ENEMY 1

#endif

